#19 feat: navigation bar UI
mokumoku-lovers/moku-moku-frontend pull request #32
Opened 2021-09-01 11:57 UTC by NicoleChow08

2021-09-01 17:09 UTC, Yin-Lynn-Htun commented on src/components/NavBar/NavBar.js
> +                onClick={handleClick}
I think there is no function for this onClick function for NavLink. When we click the NavLink, it will direct to the _/login_

2021-09-01 17:12 UTC, Yin-Lynn-Htun commented on src/components/NavBar/NavBar.js
> +                onClick={handleClick}
```suggestion
```

2021-09-01 17:19 UTC, Yin-Lynn-Htun commented on src/components/NavBar/SearchBar.js
> +import icon from "../../src/icon.svg"
Path for logo and icon are not found.
```suggestion
import icon from "'../../logo.svg'"
```

2021-09-01 17:22 UTC, Yin-Lynn-Htun requested changes
Great work! Most of them are working perfectly.
Path for logo and icon are not found in searchBar.js and I think there is no function for onClick at NavLink components in NavBar.js

2021-09-02 12:04 UTC, JiahuiChen99 commented
> Great work! Most of them are working perfectly.
> Path for logo and icon are not found in searchBar.js and I think there is no function for onClick at NavLink components in NavBar.js

Great code review @Yin-Lynn-Htun ! 👍

2021-09-16 15:35 UTC, closed without merging