Feature/ranking page list items/35
mokumoku-lovers/moku-moku-frontend pull request #38
Opened 2021-09-23 16:37 UTC by Yin-Lynn-Htun

Rank list item for ranking page.
I commited the wrong file ( _RankingPage.js_ instead of _RankingListItem.module.css_ )  for 0e9e572b010b420e66104649ea4efa0e029b7f20.

2021-09-25 07:07 UTC, hatoriMain requested changes
Great work! The UI seems perfect!
Here are some tiny changes that may let our UI looks better and fit with the Figma ones.
I commented them directly on `Files changed`.
1. Height of the container.
2. Linear gradient stroke for each user's icon.

And thank you again for your hard work😊

2021-09-25 14:35 UTC, Yin-Lynn-Htun commented on src/pages/RankingPage/RankingListItem.module.css
> +}
This is so cool. I didn't know that CSS trick.

2021-09-30 05:30 UTC, hatoriMain commented
The UI seems work very well! Thank you for your contribution!

2021-09-30 05:30 UTC, merged

2021-09-30 07:59 UTC, JiahuiChen99 commented
Remember to close the branch once the branch is merged 🙇‍♀️